FROM alpine:3.17.1

ARG KUBECTL_VERSION=1.17.5

RUN apk update \
    && apk add --no-cache bash curl nmap-ncat terraform aws-cli git \
    && rm -rf /var/cache/apk/* /tmp/* /sbin/halt /sbin/poweroff /sbin/reboot

RUN curl -sL -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl &&\
    chmod +x /usr/bin/kubectl && \
    curl https://get.helm.sh/helm-v2.17.0-linux-amd64.tar.gz > ./helm.tar.gz && \
    tar -xvf ./helm.tar.gz && \ 
    mv linux-amd64/helm /usr/bin/ && \
    mv linux-amd64/tiller /usr/bin && \
    rm -rf ./helm.tar.gz linux-amd64/

RUN adduser -s /bin/bash -u 1000 -D -h /home/nonrootuser nonrootuser nonrootuser

SHELL ["/bin/bash", "-c"]

ENV PATH=$PATH:/home/nonrootuser/.local/bin 
USER nonrootuser